#!/usr/bin/env bash
jupyter lab build --minimize=False
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @plotly/dash-jupyterlab-manager
jupyter lab build







